# Generated by Django 2.1.5 on 2021-09-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(choices=[('SQL', 'SQL'), ('C#', 'C#'), ('Javascript', 'Javascript'), ('Python', 'Python')], default='', max_length=60)),
                ('Course_Number', models.IntegerField(choices=[(4, 4), (1, 1), (3, 3), (2, 2)])),
                ('Instructor_Name', models.CharField(default='', max_length=60)),
                ('Duration', models.FloatField(choices=[(6, 6), (1, 1), (2, 2)], default=0)),
            ],
        ),
    ]
