# Generated by Django 2.0.7 on 2021-09-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=60)),
                ('Course_Number', models.IntegerField()),
                ('Instructor_Name', models.CharField(default='', max_length=60)),
                ('Duration', models.FloatField(default=0)),
            ],
        ),
    ]
