# Generated by Django 2.1.5 on 2021-09-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(choices=[('Off Campus', 'Off Campus'), ('On Campus', 'On Campus')], default='', max_length=60)),
                ('Roommates', models.CharField(choices=[('NO', 'NO'), ('Yes', 'Yes')], default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Main', models.CharField(choices=[('Beef', 'Beef'), ('Chicken', 'Chicken'), ('Pork', 'Pork'), ('Vegetarian', 'Vegetarian')], default='', max_length=60)),
                ('Drinks', models.CharField(choices=[('Soda', 'Soda'), ('Milk', 'Milk'), ('Water', 'Water'), ('Juice', 'Juice')], max_length=60)),
                ('Sides', models.CharField(choices=[('Vegetable', 'Vegetable'), ('Salad', 'Salad'), ('Mac and Cheese', 'Mac and Cheese')], default='', max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='Title',
            field=models.CharField(choices=[('C#', 'C#'), ('Python', 'Python'), ('SQL', 'SQL'), ('Javascript', 'Javascript')], default='', max_length=60),
        ),
    ]
