# Generated by Django 2.0.7 on 2021-09-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Title',
            field=models.CharField(choices=[('Javascript', 'Javascript'), ('SQL', 'SQL'), ('C#', 'C#'), ('Python', 'Python')], default='', max_length=60),
        ),
    ]
