# Generated by Django 2.1.5 on 2021-09-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0002_auto_20210923_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Title',
            field=models.CharField(choices=[('SQL', 'SQL'), ('Python', 'Python'), ('Javascript', 'Javascript'), ('C#', 'C#')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='meals',
            name='Drinks',
            field=models.CharField(choices=[('Milk', 'Milk'), ('Juice', 'Juice'), ('Soda', 'Soda'), ('Water', 'Water')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='meals',
            name='Main',
            field=models.CharField(choices=[('Pork', 'Pork'), ('Vegetarian', 'Vegetarian'), ('Beef', 'Beef'), ('Chicken', 'Chicken')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='meals',
            name='Sides',
            field=models.CharField(choices=[('Vegetable', 'Vegetable'), ('Mac and Cheese', 'Mac and Cheese'), ('Salad', 'Salad')], default='', max_length=60),
        ),
    ]
