# Generated by Django 2.1.5 on 2021-09-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0003_auto_20210923_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Main', models.CharField(choices=[('Chicken', 'Chicken'), ('Vegetarian', 'Vegetarian'), ('Pork', 'Pork'), ('Beef', 'Beef')], default='', max_length=60)),
                ('Drinks', models.CharField(choices=[('Juice', 'Juice'), ('Soda', 'Soda'), ('Milk', 'Milk'), ('Water', 'Water')], default='', max_length=60)),
                ('Sides', models.CharField(choices=[('Vegetable', 'Vegetable'), ('Salad', 'Salad'), ('Mac and Cheese', 'Mac and Cheese')], default='', max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Meals',
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='Title',
            field=models.CharField(choices=[('C#', 'C#'), ('Python', 'Python'), ('SQL', 'SQL'), ('Javascript', 'Javascript')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='housing',
            name='Title',
            field=models.CharField(choices=[('On Campus', 'On Campus'), ('Off Campus', 'Off Campus')], default='', max_length=60),
        ),
    ]
