# Generated by Django 2.0.7 on 2021-09-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0003_auto_20210922_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Course_Number',
            field=models.IntegerField(choices=[('001', 1), ('004', 4), ('003', 3), ('002', 2)]),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='Duration',
            field=models.FloatField(choices=[('2 yr', 2), ('6 mnth', 6), ('1 yr', 1)], default=0),
        ),
    ]
