# Generated by Django 2.0.7 on 2021-09-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0004_auto_20210922_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Course_Number',
            field=models.IntegerField(choices=[('001', 1), ('002', 2), ('003', 3), ('004', 4)]),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='Duration',
            field=models.FloatField(choices=[('1 yr', 1), ('2 yr', 2), ('6 mnth', 6)], default=0),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='Title',
            field=models.CharField(choices=[('C#', 'C#'), ('Python', 'Python'), ('SQL', 'SQL'), ('Javascript', 'Javascript')], default='', max_length=60),
        ),
    ]
