# Generated by Django 2.1.5 on 2021-09-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0004_auto_20210923_1926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='Title',
            field=models.CharField(choices=[('SQL', 'SQL'), ('C#', 'C#'), ('Javascript', 'Javascript'), ('Python', 'Python')], default='', max_length=60),
        ),
    ]
