# Generated by Django 2.0.7 on 2021-09-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0006_auto_20210922_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Title',
            field=models.CharField(choices=[('SQL', 'SQL'), ('Python', 'Python'), ('C#', 'C#'), ('Javascript', 'Javascript')], default='', max_length=60),
        ),
    ]
