# Generated by Django 2.0.7 on 2021-09-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0007_auto_20210922_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Title',
            field=models.CharField(choices=[('Python', 'Python'), ('Javascript', 'Javascript'), ('SQL', 'SQL'), ('C#', 'C#')], default='', max_length=60),
        ),
    ]
